# Generated by Django 3.2.18 on 2023-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0029_auto_20230502_0126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estimatepoint',
            unique_together=set(),
        ),
    ]
