# Generated by Django 3.2.18 on 2023-05-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0032_inbox_inboxissue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxissue',
            name='duplicate_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbox_duplicate', to='db.issue'),
        ),
    ]
